export const ROLES = {
    admin: 'admin',
    Vinicars: 'admin',
    Jirka: 'admin',
    Roman: 'admin',
    Global: 'admin',
    Autosklo: 'editor',
    Uniqa: 'editor',
    Pillow: 'editor',
    Direct: 'editor',
    AUTOUH: 'editor',
    AUTONORD: 'editor',
    DIRECTAUTO: 'editor',
    BIRNE: 'editor',
    ALLIANZ: 'editor',
    AUTOLEAS: 'editor',
    DASPOL: 'editor', 
    BOB: 'editor',
    ARVAL: 'editor',
    BUSINESS: 'editor',
    CSOB: 'editor',
    Talafova: 'editor',
    Hlavsova: 'editor',
    Horynova: 'editor',
    Autopalace: 'editor',
    CBservis: 'editor',
    CKservis: 'editor',
    TBRservis: 'editor',
    OLCservis: 'editor',
    SUMPservis: 'editor',
    DOLAK: 'editor',
    KACMACEK: 'editor',
    AUTONOVA: 'editor',
    AUTOPOLY: 'editor',

    // Všechny ostatní, co tu nejsou, budeme považovat za "user"
};
